version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
